The generator of a GAN needs to translate from coarse salient features to a more dense and detailed output (typically an image). I.e. a kind of 'inverse' to pooling layers.

NOTE: Move to cnn-basics?

references: https://machinelearningmastery.com/upsampling-and-transpose-convolution-layers-for-generative-adversarial-networks/

## UpSampling2D
By default UpSampling2D uses a nearest neighbor algorithm to fill in the new rows and columns effectively duplicating points. (‘interpolation‘ argument = ‘nearest‘). Bilinear interpolation can be specified via setting the ‘interpolation‘ argument to ‘bilinear‘ e.g. UpSampling2D(interpolation='bilinear').

Subsequent convolution layers will be trained to interpret the upsampled output and translate it into meaningful detail.

In [5]:
# example of using the upsampling layer
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

# define input data
X = asarray([[1, 2],
             [3, 4]])

# show input data for context
print(X)

# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), size=(2,2)))

# summarize the model
model.summary()

# make a prediction with the model
yhat = model.predict(X)

# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))

# summarize output
print(yhat)

[[1 2]
 [3 4]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_3 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


## Conv2DTranspose 
Conv2DTranspose performs an inverse convolution operation and thus is similar to combining the UpSampling2D and Conv2D layers into one layer in that it simultaneously upsamples and learns how to interpret the result. This is typically preferred to UpSampling2D.

In the below, stride of (2,2) doubles the size (new values assume teh value 0), weight in the single filter is set to 1 (meaning input values are multipled by 1), bias is 0 meaning nothing is added to the inputs.

In [10]:
# example of using the transpose convolutional layer
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose
# define input data
X = asarray([[1, 2],
             [3, 4]])
# show input data for context
print(X)
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
# define model
model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
# summarize the model
model.summary()
# define weights that they do nothing
weights = [asarray([[[[1]]]]), asarray([0])]
# store the weights in the model
model.set_weights(weights)
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

[[1 2]
 [3 4]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_5 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]
